// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-bwVk0nMs3sI8WglOkbXAYPUruB1YDgA',
    appId: '1:284994311059:android:12c07c25af499893524e66',
    messagingSenderId: '284994311059',
    projectId: 'vitaro-4d136',
    databaseURL: 'https://vitaro-4d136-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vitaro-4d136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8CKJcja1ZomGL5wtmmyLYEc29fqusII',
    appId: '1:284994311059:ios:92da814a6c8b027f524e66',
    messagingSenderId: '284994311059',
    projectId: 'vitaro-4d136',
    databaseURL: 'https://vitaro-4d136-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vitaro-4d136.firebasestorage.app',
    iosClientId: '284994311059-he7bdqs24rjqp30jj6pe28qvgf35sn4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitaro',
  );
}
